---
# Usage: ansible-playbook --extra-vars "primary_subdomain=mydomain domains=www.mydomain.org" import-wordpress-site.yml
- hosts: all
  vars_prompt:
  - name: "site_import_file"
    prompt: "Enter the filename containing the import data (this is usually the same as the alba username)"
    private: no
  vars:
    group_fpm: false
    ssl_host: false
  vars_files:
    - "{{ playbook_dir }}/from-alba/{{ site_import_file }}.yml"
  become: true
  roles:
  - domain-munging
  - { role: containers-on-demand, when: not group_fpm, tags: ['docker'] }
  - { role: group-php-fpm, when: group_fpm, tags: ['docker'] }
  - container-environments
  - vhost-renew
  - apps-wordpress-create
  - { role: sql-create-database, when: db_exists is failed, tags: ['database'] }
  - { role: site-import, site_dump_file: "{{ zipped_filename }}" }
  - { role: sql-import-database, import_file: "/var/www/{{ primary_subdomain }}/public_html/database.sql.gz" }
#  - site-diagnostics