- name: Try to find wp-config
  stat: "path=/var/customers/webs/{{ alba_user }}/wp-config.php"
  register: wp_config_path

- name: Set wordpress location fact
  set_fact:
    wp_path: "/var/customers/webs/{{ alba_user }}"
  when: wp_config_path.stat.exists

- name: Try to find wp-config (attempt 2)
  stat: "path=/var/customers/webs/{{ alba_user }}/public_html/wp-config.php"
  register: wp_config_path_two

- name: Set wordpress location fact (attempt 2)
  set_fact:
    wp_path: "/var/customers/webs/{{ alba_user }}/public_html"
  when: wp_config_path_two.stat.exists

- name: Retrieve domain information
  shell: "sudo -u {{ alba_user }} wp --path={{ wp_path }} option get siteurl"
  register: domain_name_cmd

- name: Find name of database
  shell: "cat {{ wp_path }}/wp-config.php | grep DB_NAME | cut -d \\' -f 4"
  register: db_name
  changed_when: false

- name: Set fact about the domain
  set_fact:
    domain_name: "{{ domain_name_cmd.stdout | replace('http://', '') | replace('https://', '') }}"
    secondary_domain: ""

- name: Set fact about subdomain
  set_fact:
    secondary_domain: " www.{{ domain_name }}"
  when: "'common.scot' not in domain_name"

- name: Dump database to database.sql.gz
  mysql_db:
    state: dump
    name: "{{ db_name.stdout }}"
    target: "{{ wp_path }}/database.sql.gz"
    # login_user: root
    # login_password: "{{ alba_mysql_root_password }}"

- name: Zip site content and database
  shell: zip -r website.zip database.sql.gz wp-content
  args:
    creates: "{{ wp_path }}/website.zip"
    chdir: "{{ wp_path}}"

- name: Download site content and database
  fetch:
    src: "{{ wp_path }}/website.zip"
    dest: "from-alba/{{ alba_user }}.zip"
    flat: true

- name: Remove the site dump
  file: "path={{ wp_path }}/website.zip state=absent"

- name: Generate a vars config to import the new site
  become: false
  local_action: "template src='{{ playbook_dir }}/vars.yml.j2' dest='{{ playbook_dir }}/from-alba/{{ alba_user }}.yml'"

- name: reset play vars
  set_fact:
    wp_config_path: false
    wp_path: false