- name: copy generic .conf files to docker volumes
  synchronize:
    src: "{{ role_path }}/files/nginx/config-inc/"
    dest: "{{ docker_volumes['docker_nginx_config_inc'] }}"
  notify: reload nginx

- name: copy group_fpm global pool settings
  copy:
    src: "fpm/{{ item }}"
    dest: "{{ docker_volumes['docker_group_php_pools'] }}"
  with_items:
    - www.conf
  notify: reload fpm

- name: copy nginx config auto-includes to /etc/nginx/conf.d
  synchronize:
    src: "{{ role_path }}/files/nginx/conf.d/"
    dest: "{{ docker_volumes['docker_nginx_config'] }}"
  notify: reload nginx

- name: A default SSL certificate-pair should exist for all vhosts when using SSL but not letsencrypt and no user certificates were provided
  command: "openssl req -new -nodes -x509 -subj /C=GB/ST=London/L=London/O=IT/CN=noflag.org.uk -days 365 -keyout {{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.key -out {{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.crt -extensions v3_ca creates={{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.crt"
  notify: reload nginx

- name: Ensure vhost prefixes exist for vhosts in /etc/nginx/sites-enabled
  synchronize:
    src: "{{ role_path }}/files/nginx/sites-enabled/"
    dest: "{{ docker_volumes['docker_sites_enabled'] }}"
  notify: reload nginx

- name: Copy health-check to default web dir
  command: "echo 'Switchboard OK' > /var/www/html/index.html"
    creates: /var/www/html/index.html