- name: Store mysql logs
  command: "docker logs {{ sqldb }}"
  register: sql_log
  changed_when: false

- name: Find root password from container log
  set_fact:
    mysql_root_password: "{{ item.split(' ')|last }}"
  when:
    - '"MySQL root Password" in item'
  with_items: "{{sql_log.stdout_lines}}"
  no_log: true
  changed_when: false

- name: Store MySQL root password to file
  copy:
    content: >
      MYSQL_PWD={{ mysql_root_password }}
      MYSQL_HOST={{ mysql_host }}
      MYSQL_TCP_PORT={{ mysql_tcp_port }}
      DB_USER=root
    dest: "{{ mysql_root_password_file }}"
    owner: root
    group: root
    mode: 0660