---
# Shell equiv:
# systemctl enable fpm-waker@$domain.socket; systemctl start fpm-waker@$domain.socket
# This command tells systemd to create a listening socket in /var/run/docker-apps/$domain. This socket listens for incoming traffic
# When received, systemd starts the docker container and then proxies the incoming traffic into it.
# We use a systemd unit template to avoid cluttering up /etc/systemd/services
- name: Create a systemd wake socket for the new container
  systemd:
    name: "fpm-waker@{{ primary_subdomain }}.socket"
    state: started
    enabled: true
  when: not container_always_active

- name: Fix bug in last task by forcing the wake socket activation
  command: /usr/local/bin/renew-fpm-socket.sh {{ primary_subdomain }}
  changed_when: false
  ignore_errors: true

- name: Ensure that no evidence of a group_fpm pool exists for this site
  include: not_group_fpm.yml