---
- name: ensure no trace of a group fpm pool exists for this site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_volumes['docker_sites_enabled'] }}/default/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_sites_enabled'] }}/php-fpm-group/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_group_php_pools'] }}/{{ primary_subdomain }}.conf"
  notify:
    - reload nginx
    - reload fpm

- name: Quick fix for user_wp_content_dir when its undefined
  set_fact:
    user_wp_content_dir: /var/www/{{ primary_subdomain }}/public_html/wp-content
  when:
    - user_wp_content_dir is not defined

- name: Set facts relating to on-demand containers
  set_fact:
    vhost_prefix: on-demand
    group_fpm: false
    socket_name: "{{ primary_subdomain }}/vhost.fpm-waker" # e.g. /var/run/docker-apps/mydomain.org/fpm-waker.sock
    parent_container: "{{ primary_subdomain }}.fpm"
    fpm_user: www-data
    webroot: /usr/src/wordpress
    # server_block_extra: |
    #   location ^~ /wp-content {
    #     alias {{ user_wp_content_dir }};
    #   }

  tags:
    - vhost
    - all

- name: ensure wp-content directory has correct owner
  file:
    path: "{{ user_site_dir }}"
    mode: 0755
    owner: "{{ fpm_user }}"
    group: www-data
    recurse: true
    state: directory