---
# tasks file for general-install
- name: Install imporant utilities
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: true
  with_items:
    - aptitude
    - nano
    - ssmtp
    - ansible
    - zip
    - unzip
    - git
    - curl
    - wget
    - docker
    - docker-compose
    - fish

- name: run apt-get upgrade
  apt: upgrade=full

- name: Change user shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items: "{{ fish_users }}"
  when: fish_users is defined
  ignore_errors: true