---
# tasks file for general-install
- name: Install imporant utilities
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: true
  with_items:
    - aptitude
    - nano
    - ssmtp
    - ansible
    - zip
    - unzip
    - git
    - curl
    - wget
    - fish
    - docker
    - systemd-docker
  tags:
    - apt

# - name: install certain python modules for docker
#   pip:
#     name: "{{ item.name }}"
#     version: "{{ item.version }}"
#     state: present
#   with_items:
#   - { name: docker, version: 2.0.0 }
#   - { name: docker-py, version: 1.10.6 }


- name: run apt-get upgrade
  apt: upgrade=full
  tags:
    - update

- name: Change user shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items: "{{ fish_users }}"
  when: fish_users is defined
  ignore_errors: true
  tags:
    - shell

- name: Copy convenience scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
  with_items:
    - docker-clean.sh
  tags:
    - bins

- name: host should have latest version of docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m) > /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose
  tags:
    - bins
    - aptfixes

# Possible instability with docker-daemon and GRPC
# - name: Install docker-squash
#   unarchive:
#     src: https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
#     dest: /usr/local/bin
#     remote_src: true