---
# tasks file for general-install
- name: Install imporant utilities
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: true
  with_items:
    - aptitude
    - nano
    - ssmtp
    - ansible
    - zip
    - unzip
    - git
    - curl
    - wget
    - dig
    - fish
    - docker
    - systemd-docker
    - python-pip
    - etckeeper
    - logwatch

- name: install certain python modules for docker
  pip:
    name: "{{ item }}"
#    version: "{{ item.version }}"
    state: present
  with_items:
  - docker
  - docker-compose

- name: run apt-get upgrade
  apt: upgrade=full

- name: Change user shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items: "{{ fish_users }}"
  when: fish_users is defined
  ignore_errors: true

- name: Copy convenience scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
  with_items:
    - docker-clean.sh

- name: host should have latest version of docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.2/run.sh
    dest: /usr/local/bin/docker-compose
    mode: 0744

# Possible instability with docker-daemon and GRPC
# - name: Install docker-squash
#   unarchive:
#     src: https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
#     dest: /usr/local/bin
#     remote_src: true