---
# Usage: ansible-playbook --extra-vars "db_user=myuser db_password=xxx db_name=sqldb" create-database.yml
- hosts: all
  vars_prompt:
    - name: "db_user"
      prompt: "Enter a database user"
      private: no
    - name: "db_name"
      prompt: "Enter a database name"
      private: no
    - name: "mysql_pwd"
      prompt: "Enter a database password (or type 'random')"
      default: "random"
      private: no
    - name: "env_path"
      prompt: "Do you want to create an environment (.env) file with the new DB values? Such a file can be sourced in bash to create shell variabls, and added to a docker run command to let a container discover its environment. If so, type the file path now or press enter for none"
      private: no
  pre_tasks:
  - name: Generate random database password
    local_action: shell tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 20
    register: generated_password
    when:
      - mysql_pwd == "random"

  - name: Store generated password
    set_fact:
      mysql_pwd: "{{ generated_password.stdout }}"
    when:
      - mysql_pwd == "random"
  roles:
    - sql-create-database