---
# Shell equivilent:
# docker run --net=docker_sqlnet --link sqldb.common.scot:sqldb.common.scot -e "MYSQL_PWD=1234" --rm mariadb sh -c 'mysqldump -hsqldb.common.scot -P3306 -uroot $db_name | gzip > /tmp/dump/$db_name.sql.gz
- name: Export database
  docker_container:
    name: "{{ db_name }}.dumpdb"
    image: "{{ mysql_image }}"
    networks:
      - name: docker_sqlnet
        link: "{{ sqldb }}"
    command: "mysqldump -u$DB_USER {{ db_name }} | gzip -9 > {{ dump_path }}"
    volumes:
      - "{{ dump_path }}:{{ dump_path }}"
    env_file: "{{ env_file }}"
    cleanup: yes
    detach: no