docker_image: "wordpress-php7.1-fpm-alpine-mod"
admin_user: admin
site_title: "{{ primary_subdomain }}"
use_php: yes
phproot: /usr/src/wordpress # this path is the default installation location for wordpress in alpine linux containers
extra_nginx_configs:
  - inc/wordpress.conf
user_site_dir: "/var/www/{{ primary_subdomain }}"
webroot: "{{ user_site_dir }}/public_html"
salts_file: "{{ webroot }}/salts.php"
env_path: "{{ user_site_dir }}/.env"
user_wp_content_dir: "{{ webroot }}/wp-content" # this path exists on the host and also in the group-fpm container when group_fpm is true (on-demand containers not in use)