- hosts: all
  sudo: yes
  roles:
     - { role: djcf.fish, fish_users: ['vagrant'] }
     - abaez.docker
  tasks:
    - name: Install nano
      apt:
        name: nano
        state: present

    - name: remove pre-built app containers (wp)
      docker:
        name: docker_wordpress_1
        image: wordpress
        state: absent

    - name: remove pre-built app containers (fpm)
      docker:
        name: docker_fpm_1
        image: fpm
        state: absent

    - name: host should have ansible
      apt:
        name: ansible
        state: present

#    - name: host should have latest version of docker-compose
#      shell: curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-($uname -m) > /usr/local/bin/docker-compose

    - name: Install pip
      apt:
        pkg: "{{ item }}"
        state: installed
      with_items:
        - python-dev
        - python-pip

    - name: Install Docker-py
      pip:
        name: docker-py
        version: 1.1.0
#    - name: Host should have docker.py
#      become: true
#      pip: state=present name="{{ item }}"
#      with_items:
#        - docker-py==1.2.3
#        - six==1.10.0