- hosts: all
#  roles:
#     - { role: djcf.fish, fish_users: ['vagrant'] }
#     - { role: abaez.docker, become: true }
  vars:
    fish_users: vagrant
#    rigsize: small

  tasks:
    - name: Install imporant utilities
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - nano
        - ssmtp
        - ansible
        - zip
        - unzip
        - git
        - curl
        - wget
        - docker
        - docker-compose
        - fish

    - name: Change user shell
      user:
        name: "{{ item }}"
        shell: /usr/bin/fish
      with_items: "{{ fish_users }}"
      when: fish_users | length > 0
      become: true
      ignore_errors: true

    - name: configure systemd to activate docker containers
      copy: src={{ item }} dest=/etc/systemd/system/ owner=root group=root mode=655
      with_fileglob:
      - ../../systemd.services/*
      notify: reload systemd
      become: true

    - name: install a 'ghost' wordpress directory for nginx to test file existence against during requests
      become: yes
      unarchive:
        src: https://wordpress.org/latest.zip
        dest: /var/lib
        remote_src: true
        creates: /var/lib/wordpress

    - include: ../add-vhosts/inc/alpine-tasks-find-mysql-root-password-from-docker.yml

    - name: set fact -- rigsize (medium)
      set_fact:
        rigsize: "medium"
      when:
        - ansible_memtotal_mb|int >= 128

    - name: set fact -- rigsize (large)
      set_fact:
        rigsize: "large"
      when:
        - ansible_memtotal_mb|int >= 1024

    - name: set fact -- rigsize (huge)
      set_fact:
        rigsize: "huge"
      when:
        - ansible_memtotal_mb|int >= 3000

    - name: Template out the best-matching MySQL configuration file
      template: "src=resources/mysql/my-{{ rigsize }}.cnf.j2 dest=/vagrant/docker/sqldb/my.cnf"

#    - name: set fact -- number of worker_connections
#      command: ulimit -n
#      register: worker_connections
#      changed_when: false
#      become: true

#    - name: template out a new nginx.conf file with the appropriate number of workers for this host
#      template: src=resources/nginx.conf.j2 dest="/vagrant/docker/switchboard/nginx.conf"
#      become: true

#    - name: host should have latest version of docker-compose
#      shell: curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-($uname -m) > /usr/local/bin/docker-compose

#    - name: Install pip
#      apt:
#        pkg: "{{ item }}"
#        state: installed
#      with_items:
#        - python-dev
#        - python-pip

#    - name: Install Docker-py
#      pip:
#        name: docker-py
#        version: 1.1.0

#    - name:
#    - name: Host should have docker.py
#      become: true
#      pip: state=present name="{{ item }}"
#      with_items:
#        - docker-py==1.2.3
#        - six==1.10.0

  handlers:
    - name: reload systemd
      become: yes
      command: systemctl daemon-reload
      changed_when: false