galaxy_info:
  author: danielle
  description: see readme.md
  company: CommonWeal
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: []
dependencies:
  - { role: install-web, tags: ['install'] }
  - common
  - sql-base