---
- name: Copy database to remote host
  copy:
    src: "{{ local_import_file }}"
    dest: "/tmp"
  when: local_import_file is defined

- name: Set path to upload (user upload)
  set_fact:
    import_file: "/tmp/{{ local_import_file }}"
  when: local_import_file is defined

- name: Set path to database file (not user upload and no import_file supplied)
  set_fact:
    import_file: "{{ user_site_dir }}/database.sql.gz"
  when: 
    - user_site_dir is defined
    - import_file is not defined

# Shell equiv
# docker run --env-file .env --rm -v public_html/database.sql.gz:/tmp/database.sql.gz:ro -it gists/mariadb ash
- name: Import database
  docker_container:
    image: "{{ mysql_image }}"
    networks:
      - name: docker_sqlnet
        links:
          - "{{ sqldb }}:{{ mysql_host }}"
    #command: "cat /tmp/createdb.sql | mysql -f -h{{ db_host }} -P{{ db_port }} -uroot -p$MYSQL_ROOT_PASSWORD"
    command: sh -c 'gunzip -c /tmp/database.sql.gz | mysql -f -u"$DB_USER" "$DB_NAME"'
    env_file: "{{ env_path }}"
    cleanup: yes
    detach: no
    volumes: "{{ import_file }}:/tmp/database.sql.gz:ro"
    name: "{{ db_name }}_sqlimport"
  when:
    - env_path is defined
    - env_path != ""