galaxy_info:
  author: danielle
  description: installs d7 as a containerized fpm process
  company: CommonWeal
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: []
dependencies:
  - apps-drupal-base
  - vhost-renew