---
# ???
- include: set_facts.yml

- name: project directory should exist
  file: "path={{ user_site_dir }} state=directory recurse=true"
  when:
    - user_site_dir is defined

# Shell: if [ -e /var/www/$domain/.env ]
- name: ENV file should exist
  stat: "path={{ env_path }}"
  register: environment_exists
  failed_when: not environment_exists.stat.exists
  ignore_errors: yes

- include: environment_not_exists.yml
  when: environment_exists is failed

# - include: environment_exists.yml
#   when: environment_exists is succeeded