---
- name: Set facts about php-fpm group
  set_fact:
    container_always_active: true
    use_php: true
    vhost_prefix: php-fpm-group
    group_fpm: true
    socket_name: php-fpm
    state: started
    parent_container: "{{ group_fpm_container }}"

- name: Find out whether group-fpm container is running
  command: "docker inspect --format='{%raw%}{{json .State.Running}}{%endraw%}' {{ group_fpm_container }}"
  changed_when: false
  register: fpm_container_running
  ignore_errors: true
  failed_when: fpm_container_running.stdout == 'false' or 'No such object' in fpm_container_running.stderr

# tasks file for group-php-fpm
- name: Template a new fpm-pool to the group-php-fpm container
  template:
    src: php-pool.j2
    dest: "{{ docker_volumes['docker_group_php_pools'] }}/{{ primary_subdomain }}.conf"
  vars:
    fpm_user: www-data
  when: fpm_container_running|failed

- name: Ensure fpm container is started
  docker_container:
    name: "{{ group_fpm_container }}"
    state: started
  ignore_errors: true

- name: Add new user to group-fpm container
  command: "docker exec {{ group_fpm_container }} sh -c '/usr/local/bin/add-users.sh {{ db_user }}'"
  ignore_errors: true

# tasks file for group-php-fpm
- name: Template a new fpm-pool to the group-php-fpm container
  template:
    src: php-pool.j2
    dest: "{{ docker_volumes['docker_group_php_pools'] }}/{{ primary_subdomain }}.conf"
  vars:
    fpm_user: "{{ db_user }}"
  notify:
    - reload fpm