---
# tasks file for system
- include: gather-system-facts.yml
  tags: all

- include: pre-install.yml
  tags: preinstall

- include: cronable.yml
  tags: cron

- include: docker.yml
  tags: docker
  when: use_docker_assembly