---
- name: Add a group only for SFTP users
  group: name=sftp-only

- name: Remove default SFTP server
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: Subsystem sftp /usr/lib/openssh/sftp-server
    state: absent
    validate: '/usr/sbin/sshd -T -f %s'
    backup: true
  notify: restart sshd

- name: Use internal SFTP server
  blockinfile:
    dest: /etc/ssh/sshd_config
    validate: '/usr/sbin/sshd -T -f %s'
    block: |
      Subsystem sftp internal-sftp
      Match Group sftp-only
        ChrootDirectory /var/www/%u
        X11Forwarding no
        AllowTcpForwarding no
        ForceCommand internal-sftp
        AuthorizedKeysFile /var/www/%u/.ssh/authorized_keys
        PasswordAuthentication yes
  notify: restart sshd