---
- name: Get docker volume information
  shell: docker volume inspect {{ docker_volume_lbls | join(' ') }}
  register: vlm_res
  changed_when: false

- name: Set fact about the docker volumes
  set_fact: "docker_volumes={{ dict(vlm_res.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}"

- name: The following facts are now available for use by ansible
  debug: var=docker_volumes

- name: check if host is a vagrant
  stat: path=/vagrant
  changed_when: false
  register: is_vagrant

- name: set fact about host vagrancy
  set_fact:
    is_vagrant: true
#    install_path: /vagrant
  when: is_vagrant.stat.exists