---
# defaults file for containers-on-demand
container_sleeps_after: 20m
container_always_active: false
state: "{{ container_always_active|ternary('present', 'started') }}"
socket_name: "{{ primary_subdomain }}/vhost.fpm-waker" # e.g. /var/run/docker-apps/mydomain.org/fpm-waker.sock