---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars_prompt:
  - name: "primary_subdomain"
    prompt: >
      ** Primary subdomain ** ALL websites must have a primary subdomain associated with them and parked to the domain host.
      This is to ensure the website is able to stay active even if control over the top-level domain is lost or expires.
      It will be used as a unique key to identify this user's domain.
      For example, for 'example.noflag.org.uk', enter 'example'
    private: no
  - name: "domains"
    prompt: >
      ** Extra domains ** If the website has alias domains of any kind, enter them now, separated by a space
      The first domain entered will become the primary domain if relevent, and a www. subdomain automatically created.
    private: no
    default: ""
  - name: "zones"
    prompt: >
      ** Domain zones ** If any domains entered above have zones other than the primary zone, enter them here. 
      A zone is ussually equvilent to the top-level domain in a hierachy (e.g. for 'extra domain' "test.example.org", the zone is 'example.org')
      There must be a 1-1 mapping with the extra domains you entered s.t. each extra domain corresponds to a zone in this list.
      If you press enter without typing a zone, either the primary zone will be used or all extra domains entered will also become zones."
  become: true
  vars:
    group_fpm: false
    use_php: false
  roles:
  - domain-munging
  - { role: vhost-renew, tags: ['vhost'] }
#  - site-diagnostics