---
# Usage: ansible-playbook --extra-vars "domain=mydomain.orgk" plays/wordpress/remove-wordpress.yml
- hosts: all
  vars_prompt:
    - name: "primary_subdomain"
      prompt: "Enter the primary sub-domain you would like to remove"
      private: no
    - name: "backup"
      prompt: "Would you like to backup this website first? (type anything other than 'no')"
      default: "no"
      private: no
    - name: "remove"
      prompt: "By default, this play will *not* remove web content from the host. Would you like to do that now? (type anything other than 'no')"
      default: "no"
      private: no
  become: true
  roles:
    - { role: site-export, when: backup != "no", dump_path: "/var/www/{{ primary_subdomain }}/database.sql.gz" }
    - vhost-remove
    - { role: sql-remove-database, ignore_errors: true }
    - { role: container-remove, container_name: "{{ primary_subdomain }}.fpm" }
  post_tasks:
    - name: fetch site export
      fetch:
        src: "/var/www/{{ primary_subdomain }}/site_export.zip"
        dest: "{{ primary_subdomain }}.zip"
      when: backup != "no"

    - name: Remove all web content from host
      file:
        state: absent
        path: "/var/www/{{ primary_subdomain }}"
      when: remove != "no"