---
- name: Remove relevant files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_volumes['docker_sites_enabled'] }}/default/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_sites_enabled'] }}/php-fpm-group/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_sites_enabled'] }}/on-demand/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_sites_enabled'] }}/other-external/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_sites_enabled'] }}/container-apps/{{ primary_subdomain }}.conf"
    - "{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.pem"
    - "{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.key"
    - "{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.crt"
    - "{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.cert"
    - "{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.dhparam.pem"
    - "{{ docker_volumes['docker_group_php_pools'] }}/{{ primary_subdomain }}.conf"
    - "/etc/systemd/system/socket.target.wants/fpm-waker@{{ primary_subdomain }}.socket"
    - "/var/run/docker-apps/{{ primary_subdomain }}/"
  notify: reload nginx

# todo: add reload fpm handler?