---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars_prompt:
  - name: "primary_subdomain"
    prompt: >
      ** Primary subdomain ** ALL websites must have a primary subdomain associated with them and parked to the domain host.
      This is to ensure the website is able to stay active even if control over the top-level domain is lost or expires.
      It will be used as a unique key to identify this user's domain.
      For example, for 'example.noflag.org.uk', enter 'example'.
    private: no
  # - name: "primary_domain"
  #   prompt: "\n\n** Primary domain **\nIf the website has a primary top-level domain associated with it you may enter it now, or press enter to use the primary subdomain. \n\nIf you do enter a value, a www. alias will automatically be added as a subdomain. \n\nEnter a primary domain for Wordpress (or press enter): "
  #   private: no
  #   default: ""
  - name: "domains"
    prompt: >
      ** Extra domains ** If the website has alias domains of any kind, enter them now, separated by a space.
      will become the primary domain or just press enter to use the primary_subdomain"
    private: no
    default: ""
  - name: "site_title"
    prompt: "\n\nEnter a 'site title' for Wordpress:"
    private: no
    default: "My new website"
  - name: "admin_email"
    prompt: >
      Enter the site administrator's email address for the purposes of WP account password recovery. 
      The new admin account password will be sent to this address by Wordpress
    private: no
  - name: "zones"
    prompt: >
      ** Domain zones ** If any domains entered above have zones other than the primary zone, enter them here. 
      A zone is ussually equvilent to the top-level domain in a hierachy (e.g. for 'extra domain' "test.example.org", the zone is 'example.org')
      There must be a 1-1 mapping with the extra domains you entered s.t. each extra domain corresponds to a zone in this list.
      If you press enter without typing a zone, either the primary zone will be used or all extra domains entered will also become zones."
  vars:
    group_fpm: true
    ssl_host: false
    lets_encrypt: false
    force_letsencrypt: false
  become: true
  pre_tasks:
    - debug:
        var: "{{ item }}"
      with_items:
        - group_fpm
        - ssl_host
  roles:
  - { role: domain-munging, tags: ['always'] }
  - { role: containers-on-demand, when: not group_fpm, tags: ['docker'] }
  - { role: group-php-fpm, when: group_fpm, tags: ['docker'] }
  - { role: apps-wordpress-create, tags: ['wordpress'] }
  - vhost-renew
  - { role: sql-create-database, when: db_exists|failed, tags: ['database'] }
  - { role: apps-wordpress-install-new, tags: ['wordpress'] }
#  - site-diagnostics
#  - play-audit