---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars_prompt:
  - name: "primary_subdomain"
    prompt: "** Primary subdomain **\nALL websites must have a primary subdomain associated with them and parked to the domain host.\nThis is to ensure the website is able to stay active even if control over the top-level domain is lost or expires. It will be used as a unique key to identify this user's domain.\n\nFor example, for 'example.noflag.org.uk', enter 'example'. \n\nEnter a primary subdomain"
    private: no
  - name: "primary_domain"
    prompt: "\n\n** Primary domain **\nIf the website has a primary top-level domain associated with it you may enter it now, or press enter to use the primary subdomain. \n\nIf you do enter a value, a www. alias will automatically be added as a subdomain. \n\nEnter a primary domain for Wordpress (or press enter): "
    private: no
    default: ""
  - name: "domains"
    prompt: "\n\n** Extra domains **\nIf the website has alias domains of any kind, enter them now, separated by a space"
    private: no
    default: ""
  - name: "site_title"
    prompt: "\n\nEnter a 'site title' for Wordpress:"
    private: no
    default: "My new website"
  - name: "admin_email"
    prompt: "\n\nEnter the site administrator's email address for the purposes of WP account password recovery. The new admin account password will be sent to this address by Wordpress"
    private: no
  vars:
    group_fpm: true
  become: true
  pre_tasks:
    - debug:
        var: group_fpm
  roles:
  - domain-munging
  - { role: containers-on-demand, when: not group_fpm }
  - container-environments
  - { role: group-php-fpm, when: group_fpm }
  - apps-wordpress-create
  - vhost-renew
  - { role: sql-create-database, when: db_exists|failed }
  - apps-wordpress-install-new
  - site-diagnostics