---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars_prompt:
  - name: "domain"
    prompt: "Enter a fully-qualified domain name. It will be added to DNS, a vhost record will be created, and it will be used as a unique key for the site on the server."
    private: no
  - name: "subdomain"
    prompt: "All top-level domain websites must also have a *.noflag.org.uk subdomain. This is to ensure the website is able to stay active even if control over the top-level domain is lost or expires. Please enter the subdomain now. If the default domain is already a subdomain of .noflag.org.uk, leave this field blank"
    private: no
  - name: "site_dump_file"
    prompt: "Enter the file name containing a zipped archive of the site. It should be structured such that the sql dump is named database.sql.gz, and is gzipped in the root of the archive which also contains the wp-content directory"
    private: no
  become: true
  roles:
  - vhost-renew
  - containers-on-demand
  - { role: container-environments, base_id: "{{ domain }}" }
  - apps-wordpress-create
  - { role: site-import }