---
- name: Unzip site dump
  unarchive:
    src: "{{ playbook_dir }}/{{ site_dump_file }}"
    dest: "{{ user_site_dir }}/public_html"

- name: ensure wp-content directory has correct owner
  file:
    path: "{{ user_site_dir }}"
    mode: 0750
    owner: www-data
    group: www-data
    recurse: true