version: '2'

# Runs the main LEMP container assembly minus php.
# Nginx used as a "switchboard" vhost controller
# Pre-builds wordpress-php for all sites globally to speed up runtime
# Last part is optional for this process.
# If using a separate mysql server, mysql part is not recomended
# @author daniel

#

services:
 # Pre-builds the fpm service for when its needed
  fpm:
    build: fpm
    image: fpm
    command: /bin/true
  # Pre-builds a wordpress image for when its needed
  # Add wordpress as a child container using fpm
  wordpress:
    build: apps/wordpress
    image: wordpress
    #depends_on:
    #  - fpm
    command: /bin/true
  # switchboard manages vhosts
  switchboard:
    # optionally build the image instead of pulling nginx from repo:
    #build: switchboard
    #image: nginx
    image: nginx
    restart: always # unless-stopped?
    container_name: switchboard
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker-apps:/var/run/docker-apps
      - nginx_config:/etc/nginx/conf.d
      - nginx_config_inc:/etc/nginx/inc:ro
      - vhost_config:/etc/nginx/vhost.d:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./switchboard/nginx.conf:/etc/nginx/nginx.conf:ro
      - sites_enabled:/etc/nginx/sites-enabled:ro
      - ssl_certs:/etc/nginx/certs:ro
      - /var/www:/var/www:ro
  # dockergen listens to the docker socket and automatically generates vhosts when containers are started
  # It is not used for the on-demand containerized vhosts like php/fpm apps
  # see https://index.docker.io/u/jwilder/nginx-proxy/
  dockergen:
    # optionally, build the image first and don't use the version on docker-hub:
    #build: dockergen
    #image: dockergen
    # or use the pre-built version on dockerhub
    image: jwilder/docker-gen
    container_name: dockergen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # IMPORTANT: Do NOT use without customized template. Will enable STS and bad things will happen:
      - ./dockergen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    # todo: add :rw
    volumes_from:
      - switchboard
    command: -notify-sighup switchboard -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  database:
    #env_file: env
    image: mariadb
    restart: always
    container_name: sqldb.noflag.org.uk
    volumes:
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - sqlnet

volumes:
  # This is where the MariaDB database files are kept
  sqldata:
    driver: local
  # This maps to /etc/nginx/conf.d in containers which read/write to that location (currently dockergen and switchboard)
  # It's included into the nginx server config by nginx's main config file /etc/nginx.conf
  # the container vhosts in nginx_config/default.conf are automatically regenerated by dockergen when containers arrive and leave
  nginx_config:
    driver: local
  # Dockergen automatically includes files in this location into the inside of each docker container's vhost's server { } block
  vhost_config:
    driver: local
  # Files in this location are available for per-vhost or server-wide include manually.
  # Nothing here is automatically included into the server config. Maps to /etc/nginx/inc
  nginx_config_inc:
    driver: local
  # Designed for htpasswd info. Maps to /etc/nginx/htpasswd
  htpasswd:
    driver: local
  # This directory contains vhost config files for each container, except the ones which dockergen auto-generates.
  # Most files here are generated by ansible. They can be edited manually if needed and the directory contents is included automatically
  sites_enabled:
    driver: local
  # Most SSL certificates live here, except for letsencrypt certs.
  # Includes the master server's default SSL cert and any supplied by clients.
  # If the cert exists, it will be automatically included by both dockergen and ansible.
  ssl_certs:
    driver: local

networks:
  sqlnet: