FROM alpine

RUN apk add \
    curl \
    git \
    ssmtp \
    zip \
    unzip \
    php5-cli \
    php5-mysql \
    php5-intl \
    php5-curl \
    php5-fpm \
    php5-gd \
    php-pear
RUN curl -skSL https://getcomposer.org/installer | php
RUN curl -skSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp && chmod 755 /usr/local/bin/wp
COPY www.conf /etc/php5/fpm/pool.d/www.conf
RUN cd /var/lib && \
    curl -skSL http://wordpress.org/latest.zip > wordpress.zip && \
    unzip wordpress.zip && \
    rm -f wordpress.zip

VOLUME /var/lib/wordpress/wp-content
VOLUME /var/lib/wordpress/wp-config.php

EXPOSE 9005

ENTRYPOINT /usr/sbin/php5-fpm --nodaemonize
