- name: copy generic .conf files to docker volumes
  synchronize:
    src: "{{ role_path }}/files/nginx/config-inc/"
    dest: "{{ docker_volumes['docker_nginx_config_inc'] }}"
  notify: reload nginx

- name: copy group_fpm global pool settings
  synchronize:
    src: "{{ role_path }}/files/fpm/"
    dest: "{{ docker_volumes['docker_group_php_pools'] }}"
  notify: reload fpm

- name: copy nginx config auto-includes to /etc/nginx/conf.d
  synchronize:
    src: "{{ role_path }}/files/nginx/conf.d/"
    dest: "{{ docker_volumes['docker_nginx_config'] }}"
  notify: reload nginx

# - name: fix bug where ansible didnt load the default variable
#   set_fact:
#     default_cert: default
#   when:
#     default_cert is not defined

- name: A default SSL certificate-pair should exist for all vhosts when using SSL but not letsencrypt and no user certificates were provided
  command: "openssl req -new -nodes -x509 -subj /C=GB/ST=London/L=London/O=IT/CN=common.scot -days 365 -keyout {{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.key -out {{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.crt -extensions v3_ca creates={{ docker_volumes['docker_ssl_certs'] }}/{{ default_cert }}.crt"
  notify: reload nginx

- name: Ensure vhost prefixes exist for vhosts in /etc/nginx/sites-enabled
  synchronize:
    src: "{{ role_path }}/files/nginx/sites-enabled/"
    dest: "{{ docker_volumes['docker_sites_enabled'] }}"
  notify: reload nginx

- name: Copy health-check to default web dir
  shell: echo 'Welcome to nginx on {{ inventory_hostname }}. No vhost or default vhost matched.' > /var/www/html/index.html creates=/var/www/html/index.html

- name: Copy README for htpasswd
  copy:
    src: "{{ role_path }}/files/nginx/htpasswd.md"
    dest: "{{ docker_volumes['docker_htpasswd'] }}"

- name: Copy README for vhost-config
  copy:
    src: "{{ role_path }}/files/nginx/vhost-config.md"
    dest: "{{ docker_volumes['docker_vhost_config'] }}"

- name: Copy README for htpasswd
  copy:
    src: "{{ role_path }}/files/nginx/ssl-certs.md"
    dest: "{{ docker_volumes['docker_ssl_certs'] }}"