---
- name: Project directory should exist
  file:
    path: "{{ user_wp_content_dir }}"
    state: directory
    recurse: yes

# Shell: if [ -e /var/www/$domain/public_html/salts.php ]
- name: SALTS file should exist
  stat: "path={{ salts_file }}"
  register: salts_file_exists
  ignore_errors: yes
  failed_when: not salts_file_exists.stat.exists

- include: salts-file.yml
  when: salts_file_exists|failed

- include: wp-config-overrides.yml

# shell: cp -r /var/lib/wordpress/wp-content/* /var/www/$domain/public_html/wp-content
- name: sync wp-content directories
  command: "rsync -a --stats /var/lib/wordpress/wp-content/ /var/www/{{ primary_subdomain }}/public_html/wp-content"
  changed_when: '"files transferred: 0" not in wp_content_rsync.stdout'
  register: wp_content_rsync

- name: ensure wp-content directory has correct owner
  file:
    path: "{{ user_site_dir }}"
    mode: 0750
    owner: www-data
    group: www-data
    recurse: true

# Shell equivilent:
# docker create --name $domain.fpm wordpress --net=docker_sqlnet wordpress
- name: Create Wordpress container for new site
  docker_container:
    name: "{{ parent_container }}"
    image: "{{ docker_image }}"
    state: "{{ state }}"
    hostname: "fpm.{{ primary_subdomain }}.{{ primary_domain }}"
    networks:
      - name: docker_sqlnet
        links:
        - "{{ sqldb }}:{{ mysql_host }}"
    volumes: "{{ volumes }}"
    detach: yes
    log_options:
      max_size: 25k
    env_file: "{{ env_path }}"
  when: not group_fpm
  tags:
    - docker

# Shell equivilent
# docker run --net=docker_sqlnet --env-file /var/www/$domain/.env --link sqldb.common.scot --volumes-from $parent_container --rm wordpress-php7.1-fpm-alpine-mod sh -c \
#   '/usr/local/bin/wp --allow-root --path=/usr/src/wordpress db check'
- name: Check to see if WP database exists
  command: >
    docker run 
      --env-file {{ env_path }} 
      --net=docker_sqlnet 
      --link {{ sqldb }}:{{ mysql_host }}
      --volumes-from {{ parent_container }}
      --rm
      {{ docker_image }} 
      sh -c 
        '/usr/local/bin/wp db check --allow-root --path={{ phproot }}'
  ignore_errors: yes
  failed_when: db_exists.rc != 0
  register: db_exists
  changed_when: false
  tags:
    - database