---
# Shell equivilent:
# docker run --net=docker_sqlnet --link sqldb.common.scot:sqldb.common.scot -e "MYSQL_PWD=1234" --rm mariadb sh -c 'mysql -f -hsqldb.common.scot -P3306 -uroot -e \"DROP DATABASE IF EXISTS $db_name; DROP USER '$db_user'@'%';
# - name: Remove database (docker run container)
#   docker_container:
#     name: "{{ db_name }}.removedb"
#     image: "{{ mysql_image }}"
#     networks:
#       - name: docker_sqlnet
#         links:
#           - "{{ sqldb }}:{{ mysql_host }}"
#     command: "mysql -f -uroot -e \"DROP DATABASE IF EXISTS {{ db_name }}; DROP USER '{{ db_user }}'@'%';\""
#     env_file: "{{ mysql_root_password_file }}"
#     cleanup: yes
#     detach: no

- name: Remove database (existing container option)
  command: "docker exec {{ sqldb }} mysql -u root -e \"DROP DATABASE IF EXISTS {{ db_name }};\""

- name: Remove db user (existing container option)
  command: "docker exec {{ sqldb }} mysql -u root -e \"DROP USER {{ db_user }}@'%';\""