---
# defaults file for apps-drupal-base
docker_image: "drupal7-php7.1-fpm-alpine-mod"
admin_user: admin
site_title: "{{ primary_subdomain }}"
use_php: yes
phproot: /var/www/html # this path is the default installation location for wordpress in alpine linux containers
extra_nginx_configs:
  - inc/drupal.conf