---
# defaults file for apps-drupal-base
docker_image: "drupal7-php7.1-fpm-alpine-mod"
admin_user: admin
site_title: "{{ primary_subdomain }}"
use_php: yes
phproot: /usr/src/drupal7 # this path is the default installation location for wordpress in alpine linux containers
user_site_dir: "/var/www/{{ primary_subdomain }}"
webroot: /usr/src/drupal7
extra_nginx_configs:
  - inc/drupal.conf
server_block_extra: |
  location ^~ /scripts/common/ {
    try_files $uri /index.php?$query_string;
    alias /var/www/{{ primary_subdomain }}/public_html/scripts/;
  }
  location ^~ /sites/ {
    try_files $uri /index.php?$query_string;
    alias /var/www/{{ primary_subdomain }}/public_html/sites/;
  }