---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars:
    - docker_image: "fpm"
  vars_files:
    - ../resources/vars_docker_conf.yml
    - resources/vars_db.yml
    - resources/vars_php.yml
  #connection: docker
  sudo: yes
  tasks:
    - include: inc/tasks-add-vhost.yml
    - include: inc/tasks-add-container.yml
    - include: inc/tasks-create-database.yml

    # Shell equivilent:
    # docker create --name $domain.fpm wordpress --net=docker_sqlnet --volumes {} wordpress
    - name: Create php container for new site
      docker_container:
        name: "{{ domain }}.fpm"
        image: "{{ docker_image }}"
        state: "{{ state }}"
        networks:
          - name: docker_sqlnet
            link: "{{ db_host }}"
        volumes:
          - "/var/run/docker-apps/{{ domain }}:/var/run/docker-apps"
          - "/var/www/{{ domain }}/public_html/wp-content:/var/lib/wordpress/wp-content"
          - "/etc/ssmtp:/etc/ssmtp:ro"
        env_file: "/var/www/{{ domain }}/.env"
      become: yes

    - action: uri url={{ transport }}://{{ domain }} return_content=yes
      register: test_success
      when: subdomain == ""

    - action: uri url={{ transport }}://{{ subdomain }} return_content=yes
      register: test_success
      when: subdomain != ""

    - fail: msg='The new vhost does not appear to be accessible'
      when: "'Wordpress' not in test_success.content"