---
# Usage: ansible-playbook --extra-vars "domain=mydomain.org subdomain=mysubdomain.noflag.org.uk" add-wordpress-vhost.yml
- hosts: all
  vars:
    - image: "wordpress"
    - database: "sqldb.noflag.org.uk"
    - ssl_host: yes
    - ssl_method: redirect
    - subdomain: ""
    - lets_encrypt: yes
    - use_php: yes
    - container_always_active: no
    - default_cert: "default"

  #connection: docker
  sudo: yes
  tasks:
  - include: tasks-add-vhost.yml

  - name: Facts about this container 1
    set_fact:
      state: started
    when: container_always_active

  - name: Facts about this container 2
    set_fact:
      state: present
    when: not container_always_active

  - name: Facts about this database 1
    set_fact:
      db_user: "{{ domain }}_user"
      db_name: "{{ domain }}_sql"

  - name: Copy vhost template to host
    template: src=env.j2 dest="/var/www/{{ domain }}/.env"
    become: yes

  # Shell equivilent:
  # docker create --name $domain.fpm wordpress --net=docker_sqlnet --volumes {} wordpress
  - name: Create Wordpress container for new site
    docker_container:
      name: "{{ domain }}.fpm"
      image: "{{ image }}"
      state: "{{ state }}"
      networks:
        - name: docker_sqlnet
          link: sqldb.noflag.org.uk:sqldb.noflag.org.uk
      volumes:
        - "/var/run/docker-apps/{{ domain }}:/var/run/docker-apps"
        - "/var/www/{{ domain }}/public_html/wp-content:/var/lib/wordpress/wp-content"
        - "/etc/ssmtp:/etc/ssmtp:ro"
      env_file: "/var/www/{{ domain }}/.env"
    become: yes

    # Shell: if [ -e /var/www/$domain/.env ]
  - name: SALTS file should exist
    stat: path="/var/www/{{ domain }}/.env"
    register: salts_file_exists
    ignore_errors: yes

    # Shell: wget https://api.wordpress.org/secret-key/1.1/salt /var/www/$domain/public_html/wp-content/salts.php
  - name: Create new unique keys for WP auths
    get_url:
      url: https://api.wordpress.org/secret-key/1.1/salt
      dest: "/var/www/{{ domain }}/public_html/wp-content/salts.php"
    become: yes
    when: not salts_file_exists

    # Shell: echo "<?php" | cat /var/www/$domain/public_html/wp-content/salts.php > /var/www/$domain/public_html/wp-content/salts.php
  - name: Salts should be php files
    lineinfile:
      dest: "/var/www/{{ domain }}/public_html/wp-content/salts.php"
      regexp: '^php'
      insertbefore: BOF
      line: '<?php'
    become: yes
    when: not salts_file_exists

  # Shell equivilent
  # docker run --net=docker_sqlnet --env-file /var/www/$domain/.env --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from $domain.fpm --rm wordpress sh -c '/usr/local/bin/wp db check --allow-root --path=/var/lib/wordpress'
  - name: Check to see if WP database exists
    command: "docker run --env-file /var/www/{{ domain }}/.env --net=docker_sqlnet --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from {{ domain }}.fpm --rm wordpress sh -c '/usr/local/bin/wp db check --allow-root --path=/var/lib/wordpress'"
    ignore_errors: yes
    failed_when: db_exists.rc != 0
    register: db_exists
    become: yes

  # Shell equivilent:
  # docker run --net=docker_sqlnet --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from {{ domain }}.fpm --rm mariadb exec mysql -hsqldb.noflag.org.uk -P3306 -uroot -p$MYSQL_ENV_MYSQL_ROOT_PASSWORD -e "CREATE USER '$db_user'@'%' IDENTIFIED BY 'password'; CREATE DATABASE '$db_name; ASSIGN ALL ON '$db_name'.* to '$db_user'@'%'"
  - name: Create database
    docker_container:
      name: "{{ domain }}.db-user-exists"
      image: mariadb
      networks:
        - name: docker_sqlnet
          link: sqldb.noflag.org.uk:sqldb.noflag.org.uk
      command: mysql -hsqldb.noflag.org.uk -P3306 -uroot -p$MYSQL_ENV_MYSQL_ROOT_PASSWORD -e "CREATE USER '{{ db_user }}'@'%' IDENTIFIED BY 'password'; CREATE DATABASE '{{ db_name }}'; ASSIGN ALL ON '{{ db_name }}'.* to '{{ db_user }}'@'%'"
      cleanup: yes
      detach: yes
    when: db_exists.rc != 0
    become: yes

  # Shell equvilent:
  # docker run --net=docker_sqlnet --env-file /var/www/{{ domain }}/.env --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from {{ domain }}.fpm --rm wordpress sh -c '/usr/local/bin/wp --allow-root --path=/var/lib/wordpress core is-installed'
  - name: Check to see if WP is installed already
    command: "docker run --net=docker_sqlnet --env-file /var/www/{{ domain }}/.env --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from {{ domain }}.fpm --rm wordpress sh -c '/usr/local/bin/wp core install is-installed --allow-root --path=/var/lib/wordpress'"
    ignore_errors: yes
    failed_when: wp_was_installed.rc != 0
    register: wp_was_installed
    become: yes

  # Shell equivilent
  # docker run --net=docker_sqlnet --link sqldb.noflag.org.uk:sqldb.noflag.org.uk --volumes-from {{ domain }}.fpm --rm wordpress sh -c '/usr/local/bin/wp --allow-root --path=/var/lib/wordpress' core install --url={{ transport }}://{{ domain }} --admin_email={{ admin_email }}'
  - name: Install Wordpress database if not
    docker_container:
      command: "/usr/local/bin/wp core install --allow-root --path=/var/lib/wordpress --url={{ transport }}://{{ domain }} --admin_email={{ admin_email }}"
      name: "{{ domain }}-installer.fpm"
      image: "{{ image }}"
      networks:
        - name: docker_sqlnet
          link: sqldb.noflag.org.uk:sqldb.noflag.org.uk
      volumes_from:
        - "{{ domain }}.fpm"
      cleanup: yes
      detach: yes
      env_file: "/var/www/{{ domain }}/.env"
    when: wp_was_installed.rc != 0
    become: yes