---
# Usage: ansible-playbook --extra-vars "db_user=myuser db_password=xxx db_name=sqldb" create-database.yml
- hosts: all
  vars:
    - db_port: 3306
    - db_host: sqldb.noflag.org.uk
  vars_prompt:
    - name: "db_user"
      prompt: "Enter a database user"
    - name: "db_name"
      prompt: "Enter a database name"
    - name: "db_password"
      prompt: "Enter a database password (or type 'random')"

  #connection: docker
  tasks:

  - name: Generate random database password
    local_action: shell tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 20
    register: generated_password
    when:
      - db_password == "random"

  - name: Store generated password
    set_fact:
      db_password: "{{ generated_password.stdout }}"
    when:
      - db_password == "random"

  - include: inc/tasks-create-database.yml