---
# Usage: ansible-playbook --extra-vars "domain=mydomain.orgk" remove-wordpress-vhost.yml
- hosts: all
  vars:
    - docker_image: "wordpress"
  vars_prompt:
    - name: "domain"
      prompt: "Enter the domain you would like to remove"
  vars_files:
    - /resources/vars_db.yml

  tasks:
  # Shell equivilent:
  # docker rm -f $domain.fpm
  - name: Remove Wordpress container
    docker_container:
      name: "{{ domain }}.fpm"
      state: absent
    become: yes

  - include: inc/tasks-dump-database.yml

  # shell equiv: zip -r /var/www/{{ domain }}/{{ domain }}.zip /var/www/{{ domain }}/public_html /var/www/{{ domain }}/{{ db_name }}.sql.gz
  - name: Compress backup files
    archive:
      path:
        - "/var/www/{{ domain }}/public_html"
        - "/var/www/{{ domain }}/{{ db_name }}.sql.gz"
      dest: "/var/www/{{ domain }}/{{ domain }}.zip"
      format: zip
    become: yes

  - include: inc/tasks-remove-database.yml
  - include: inc/tasks-remove-vhost.yml