- name: Facts about this vhost 1
  set_fact:
    transport: http
  when: not ssl_host

- name: Facts about this vhost 2
  set_fact:
    transport: https
  when: ssl_host

- name: Check whether a unique diffie-helman key exists for this vhost
  command: "docker exec -it switchboard test -e /etc/nginx/certs/{{ domain }}.dhparam.pem"
  become: yes
  ignore_errors: yes
  register: dhparam_exists
  when:
    - ssl_host
    - not lets_encrypt
  ignore_errors: yes
  failed_when: false

- name: Check whether vhost already exists
  command: "docker exec -it switchboard test -e /etc/nginx/sites-enabled/{{ domain }}"
  become: yes
  ignore_errors: yes
  register: vhost_exists
  when:
    - ssl_host
    - not lets_encrypt
  ignore_errors: yes
  failed_when: false

- name: Generate unique diffie-helman seed when using SSL but not letsencrypt
  command: openssl dhparam -out /tmp/dhparam.pem 2048
  when:
    - ssl_host
    - not lets_encrypt
    - not dhparam_exists

- name: Add unique diffie-helman seed to vhost when using SSL but not letsencrypt
  command: "docker cp /tmp/dhparam.pem swithboard:/etc/nginx/certs/{{ domain }}.dhparam.pem"
  when:
    - ssl_host
    - not lets_encrypt
    - not dhparam_exists

- name: Check if an SSL certificate exists locally (NB careful not to check into version control if so)
  local_action: "stat path={{ domain }}.crt"
  register: local_ssl_cert
  ignore_errors: yes
  when:
    - ssl_host
    - not lets_encrypt

- name: Check if an SSL key exists locally (NB careful not to check into version control if so)
  local_action: "stat path={{ domain }}.key"
  register: local_ssl_key
  ignore_errors: yes
  when:
    - ssl_host
    - not lets_encrypt

- name: Upload SSL certificate into vhost when using SSL but not letsencrypt
  copy: src={{ domain }}.crt dest=/tmp/vhost.crt
  become: yes
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key.stat.exists
    - local_ssl_cert.stat.exists

- name: Upload SSL key into vhost when using SSL but not letsencrypt
  copy: src={{ domain }}.key dest=/tmp/vhost.key
  become: yes
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key.stat.exists
    - local_ssl_cert.stat.exists

- name: Copy SSL certificate to docker host
  command: "docker cp /tmp/vhost.cert switchboard:/etc/nginx/certs/{{ domain }}.cert"
  become: yes
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key.stat.exists
    - local_ssl_cert.stat.exists

- name: Copy SSL key to docker host
  command: "docker cp /tmp/vhost.key switchboard:/etc/nginx/certs/{{ domain }}.key"
  become: yes
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key.stat.exists
    - local_ssl_cert.stat.exists

- name: Copy vhost template to host
  template: src=vhost.j2 dest=/tmp/vhost
  become: yes
  when: not vhost_exists

- name: Copy vhost template to docker
  command: "docker cp /tmp/vhost switchboard:/etc/nginx/sites-enabled/{{ domain }}"
  become: yes
  when: not vhost_exists

- name: Reload nginx configuration
  command: "docker exec -it switchboard nginx -s reload"
  become: yes
  when: not vhost_exists