---
# defaults file for system
rigsize: small
is_vagrant: false
install_path: /usr/local/web
remote_path: https://github.com/djcf/wordpress-fpm-docker.git
mysql_tcp_port: 3306
mysql_unix_port: /run/mysqld/mysqld.sock
use_docker_assembly: true