---
mysql_image: gists/mariadb #yobasystems/alpine-mariadb
db_socket: /run/mysqld/mysqld.db_socket
env_values: # what env values might we want to load from the environment file ?
  - db_name
  - mysql_pwd
  - db_user
  - mysql_unix_port
  - mysql_host
  - mysql_tcp_port
mysql_root_password_file: /etc/mysql_root_password.txt