galaxy_info:
  author: daniel
  description: updates all wordpress containers and sites to latest version from docker hub
  company: CommonWeal
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: []
dependencies:
  - apps-wordpress-base