- name: Store mysql logs when the root password file isn't found
  command: "docker logs {{ sqldb }}"
  register: sql_log
  changed_when: false

- name: Find root password from container log when the root password file isn't found
  set_fact:
    mysql_root_password: "{{ item.split(' ')|last }}"
  when:
    - '"MySQL root Password" in item'
  with_items: "{{sql_log.stdout_lines}}"
  no_log: true
  changed_when: false

- name: Store MySQL root password to file when the root password file isn't found
  copy:
    content: "{{ mysql_root_password }}"
    dest: /etc/mysql_root_password.txt
    owner: root
    group: root
    mode: 660