- name: Load MySQL root password from file
  stat: path="/etc/mysql_root_password.txt"
  register: mysql_pw_file
  failed_when: not mysql_pw_file.stat.exists
  ignore_errors: yes

- name: Set MySQL root password from file
  slurp:
    src: /etc/mysql_root_password.txt
  register: mysql_root_password_file
  when: mysql_pw_file|succeeded
  become: yes

- name: Set MySQL root password fact
  set_fact:
    mysql_root_password: "{{ mysql_root_password_file.content | b64decode }}"
  when: mysql_pw_file|succeeded

- include: tasks-find-mysql-root-password-from-docker.yml
  when: mysql_pw_file|failed

- name: Print root password
  debug:
    var: mysql_root_password