---
# Shell equivilent:
# docker run --net=docker_sqlnet --link sqldb.noflag.org.uk:sqldb.noflag.org.uk -e "MYSQL_PWD=1234" --rm mariadb sh -c 'mysqldump -hsqldb.noflag.org.uk -P3306 -uroot $db_name | gzip > /tmp/dump/$db_name.sql.gz
- name: Export database
  docker_container:
    name: "{{ domain }}.dumpdb"
    image: mariadb
    networks:
      - name: docker_sqlnet
        link: "{{ db_host }}"
    command: "mysqldump -h\"{{ db_host }}\" -P\"{{ db_port }}\" -uroot {{ db_name }} | gzip > /tmp/dump/{{ db_name }}.sql.gz"
    volumes:
      - "/var/www/{{ domain }}/data:/tmp/dump"
    env:
      MYSQL_PWD: 1234
    cleanup: yes
    detach: yes
  become: yes