---
- name: Facts about this container 1
  set_fact:
    state: started
  when: container_always_active

- name: Facts about this container 2
  set_fact:
    state: present
  when: not container_always_active

- name: Project directory should exist
  file:
    path: "/var/www/{{ domain }}/{{ install_path }}"
    state: directory
    recurse: yes

# Shell equiv:
# systemctl enable fpm-waker@$domain.socket; systemctl start fpm-waker@$domain.socket
# This command tells systemd to create a listening socket in /var/run/docker-apps/$domain. This socket listens for incoming traffic
# When received, systemd starts the docker container and then proxies the incoming traffic into it.
# We use a systemd unit template to avoid cluttering up /etc/systemd/services
- name: Create a systemd wake socket for the new container
  systemd:
    name: "fpm-waker@{{ domain }}.socket"
    state: started
    enabled: true
  when: not container_always_active