[alba]
alba.noflag.org.uk

[old-hosts]
alba.noflag.org.uk

[new-hosts]
emma.noflag.org.uk
rudolph.noflag.org.uk
ethel.noflag.org.uk

[mail-hosts]
emma.noflag.org.uk

[web-hosts]
alba.noflag.org.uk

[proxy-hosts]
rudolph.noflag.org.uk

[iceland-hosts]
emma.noflag.org.uk
alba.noflag.org.uk
rudolph.noflag.org.uk

[paris-hosts]
ethel.noflag.org.uk

[list-hosts]
alba.noflag.org.uk

[app-hosts]
rudolph.noflag.org.uk

[dnsmaster]
rudolph.noflag.org.uk

[dnsslaves]
emma.noflag.org.uk
ethel.noflag.org.uk

[sqlhosts]
rudolph.noflag.org.uk

# [vpntor-hosts]
# ethel.noflag.org.uk