---
- name: Generate unique diffie-helman seed when using SSL but not letsencrypt
  command: "openssl dhparam -out {{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.dhparam.pem 2048 creates={{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.dhparam.pem"
  when:
    - ssl_host
    - not lets_encrypt
  notify: reload nginx

- name: Check if an SSL certificate exists locally (NB careful not to check into version control if so)
  local_action: "stat path={{ primary_subdomain }}.crt"
  register: local_ssl_cert
  failed_when: not local_ssl_cert.stat.exists
  ignore_errors: yes
  when:
    - ssl_host
    - not lets_encrypt
  changed_when: false

- name: Check if an SSL key exists locally (NB careful not to check into version control if so)
  local_action: "stat path={{ primary_subdomain }}.key"
  register: local_ssl_key
  failed_when: not local_ssl_key.stat.exists
  ignore_errors: yes
  when:
    - ssl_host
    - not lets_encrypt
  changed_when: false

- name: Upload SSL certificate into vhost when using SSL but not letsencrypt
  copy: src="{{ primary_subdomain }}.crt" dest="{{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.crt"
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key|succeeded
    - local_ssl_cert|succeeded
  notify: reload nginx

- name: Upload SSL key into vhost when using SSL but not letsencrypt
  copy: src={{ primary_subdomain }}.key dest={{ docker_volumes['docker_ssl_certs'] }}/{{ primary_subdomain }}.key
  when:
    - ssl_host
    - not lets_encrypt
    - local_ssl_key|succeeded
    - local_ssl_cert|succeeded
  notify: reload nginx

- name: Try to find a custom vhost file for inclusion
  stat: "path={{ docker_volumes['docker_vhost_config'] }}/{{ primary_subdomain }}.conf"
  register: custom_vhost_exists
  failed_when: not custom_vhost_exists.stat.exists
  ignore_errors: true
  changed_when: false

- name: Try to find an certificate for the host if letsencrypt is in use
  stat: "path={{ docker_volumes['docker_ssl_certs'] }}/{{ primary_domain }}.crt"
  register: remote_ssl_cert_exists
  ignore_errors: true
  changed_when: false
  tags:
    - letsencrypt

- name: Prevent SSL from being used before the letsencrypt certificate has been generated or signed
  set_fact:
    ssl_host: false
    first_pass: true
  when:
    - letsencrypt
    - not remote_ssl_cert_exists.stat.exists
  tags:
    - letsencrypt

- name: Copy vhost template to host
  template: src=vhost.j2 dest="{{ docker_volumes['docker_sites_enabled'] }}/{{ vhost_prefix }}/{{ primary_subdomain }}.conf"
  notify: reload nginx
  register: vhost_was_installed
  validate: "docker exec -it {{ switchboard }} nginx -t"
  tags:
    - letsencrypt
    - always

- include: letsencrypt.yml
  when:
    - letsencrypt
    - first_pass is defined
  tags:
    - letsencrypt

- debug:
    msg: "A vhost for {{ primary_subdomain }} ({{ ssl_host|ternary('http','https') }}://{{ primary_domain }}) {{ vhost_was_installed.changed|ternary('has been installed','exists') }} at {{ docker_volumes['docker_sites_enabled'] }}/{{ vhost_prefix }}/{{ primary_subdomain }}.conf"