FROM debian:jessie-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /var/lib
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    curl \
    git \
    ssmtp \
    zip \
    unzip \
    mysql-client \
    php5-cli \
    php5-mysql \
    php5-intl \
    php5-curl \
    php5-fpm \
    php5-gd \
    php-pear && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists

VOLUME /etc/ssmtp

CMD ["/usr/sbin/php5-fpm", "--nodaemonize"]