---
- powerdns_zone:
    name: "zone01. {{ primary_domain }}"
    nameservers: "{{ nameservers }}"
    kind: master
    state: "{{ state }}"
    pdns_host: "{{ pdns_host }}"
    pdns_port: "{{ pdns_port }}"
    pdns_api_key: "{{ pdns_key }}"

- powerdns_record:
    name: "{{ primary_subdomain }}"
    zone: zone01.noflag.org.uk
    state: "{{ state }}"
    type: A
    content: www.noflag.org.uk. # Or IP?
    pdns_host: "{{ pdns_host }}"
    pdns_port: "{{ pdns_port }}"
    pdns_api_key: "{{ pdns_key }}"