---
# tasks file for dns-add-zone
# from https://github.com/Nosmoht/ansible-module-powerdns
# We accept a domain_list and a zone_list, both of which must be well-formed
# Any problems? Check the domain-munging role which is responsible for feeding us well-formed input

- include: add-dns.yml
  with_together:
    - zone_list
    - domain_list
  vars:
    web_server: "www.noflag.org.uk."