---
# defaults file for apps-drupal-create
volumes:
  - "/var/run/docker-apps/{{ primary_subdomain }}:/var/run"
  - "/etc/ssmtp:/etc/ssmtp:ro"
  - "/var/www/{{ primary_subdomain }}/public_html/scripts:{{ phproot }}/scripts/common"
  - "/var/www/{{ primary_subdomain }}/public_html/sites:{{ phproot }}/sites"
  - "/var/www/{{ primary_subdomain }}/public_html/private:/buildkit/app/private"