- name: Rename WP containers
  command:|
docker rmi {{ wordpress }}:oldest
docker tag {{ wordpress }}:old {{ wordpress }}:oldest
docker rmi {{ wordpress }}:old
docker tag {{ wordpress }}:latest {{ wordpress }}:old
docker rmi {{ wordpress }}:latest
docker rm -f (docker ps -qf "ancestor={{ wordpress }}:old")

# Equivilent to shell command:
# docker build -t wordpress:latest {{ path }}/wordpress
- name: Build new WP image
  docker_image:
    name: "{{ wordpress }}"
    path: "{{ path }}/apps/wordpress"
    state: present
    tag: latest

# Equivilent to shell command:
# docker run
- name: Create on-demand wordpress containers using latest WP image

- name: Execute database updates
  command: "docker run --rm --volumes-from {{ item }} --net docker_sqlnet --link {{ sqldb }} wordpress:latest sh -c '/usr/local/bin/wp --allow-root --path={{ php_root }} core update'"

- name: Execute database updates
  command: "docker run --rm --volumes-from {{ item }} --net docker_sqlnet --link {{ sqldb }} wordpress:latest sh -c '/usr/local/bin/wp --allow-root --path={{ php_root }} core update'"
  with_items: