---
# tasks file for install-archives
- name: Copy new default vhost
  copy:
    src: "{{ role_path }}/files/default_site.conf"
    dest: "{{ docker_volumes['docker_nginx_config'] }}"

# - name: Copy new docker-compose
#   copy:
#     src: "{{ role_path }}/files/docker-compose.yml"
#     dest: /usr/local

# - name: Bring up new docker containers
#   command: "docker-compose -f /usr/local/docker-compose.yml up -d"
#   tags:
#     - docker