galaxy_info:
  author: daniel
  description: exports a websites content
  company: noflag
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.3
  galaxy_tags: []
dependencies:
  - sql-dump-database